"use client";
import{useEffect,useMemo,useState}from"react";import{CalendarDays,ChevronLeft,ChevronRight,Clock,Users,Camera,Check}from"lucide-react";import{createClient}from"@/lib/supabase/client";import{bookingTypes,BookingType,money,typeLabels}from"@/lib/booking";
type Availability={start_time:string;availability:"AVAILABLE"|"ONE_LEFT"|"FULL"};
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
export function BookingWizard(){const[step,setStep]=useState(1),[date,setDate]=useState(today()),[type,setType]=useState<BookingType>("SINGLE"),[duration,setDuration]=useState(2),[start,setStart]=useState(""),[companions,setCompanions]=useState(0),[camera,setCamera]=useState("不需要"),[name,setName]=useState(""),[contact,setContact]=useState(""),[notes,setNotes]=useState(""),[slots,setSlots]=useState<Availability[]>([]),[price,setPrice]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const sb=useMemo(()=>createClient(),[]);
useEffect(()=>{setStart("");if(!sb)return;sb.rpc("slot_availability",{p_date:date,p_type:type,p_duration:duration}).then(({data})=>setSlots(data||[]));sb.rpc("calculate_price",{p_date:date,p_type:type,p_duration:duration,p_companions:companions}).then(({data})=>setPrice(data?.[0]))},[date,type,duration,companions,sb]);
useEffect(()=>{if(!sb)return;const ch=sb.channel("booking-availability").on("postgres_changes",{event:"*",schema:"public",table:"bookings"},()=>sb.rpc("slot_availability",{p_date:date,p_type:type,p_duration:duration}).then(({data})=>setSlots(data||[]))).subscribe();return()=>{sb.removeChannel(ch)}},[sb,date,type,duration]);
async function submit(){setError("");if(!sb){setError("尚未连接 Supabase。请先配置环境变量并执行数据库迁移。");return}setLoading(true);const{data,error}=await sb.rpc("create_booking_hold",{p_source:"CUSTOMER_WEB",p_name:name,p_contact:contact,p_date:date,p_start:start,p_duration:duration,p_type:type,p_companions:companions,p_camera:camera,p_notes:notes.trim()||null,p_adjustment:0});setLoading(false);if(error){setError(error.message.includes("SLOT_UNAVAILABLE")?"这个时间刚刚被其他客人预约了，请重新选择时间。":"提交失败，请检查信息后重试。");return}location.href=`/book/confirmation/${data[0].public_access_token}`}
const fallback=Array.from({length:15-duration+1},(_,i)=>({start_time:`${String(i+9).padStart(2,"0")}:00:00`,availability:"AVAILABLE" as const})),shown=slots.length?slots:fallback;
return <div className="card overflow-hidden"><div className="border-b border-[var(--line)] px-5 py-4"><div className="flex items-center justify-between text-xs font-bold muted"><span>预约信息</span><span>{step} / 3</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#f6e8ee]"><div className="h-full bg-[var(--pink)] transition-all" style={{width:`${step/3*100}%`}}/></div></div><div className="p-5 md:p-7">
{step===1&&<><h2 className="text-2xl font-black">什么时候来？</h2><label className="mt-6 block text-sm font-bold"><CalendarDays className="mr-2 inline h-4 w-4"/>选择日期</label><input className="field mt-2" type="date" min={today()} value={date} onChange={e=>setDate(e.target.value)}/><label className="mt-6 block text-sm font-bold">预约项目</label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{bookingTypes.map(t=><button key={t} className={`choice ${type===t?"active":""}`} onClick={()=>{setType(t);if(t==="PRIVATE")setCompanions(0)}}><span className="block font-black">{typeLabels[t]}</span><span className="mt-1 block text-xs muted">{t==="SINGLE"?"1 人":t==="DOUBLE"?"2 人":t==="TRIPLE"?"3 人":"独享"}</span></button>)}</div><label className="mt-6 block text-sm font-bold"><Clock className="mr-2 inline h-4 w-4"/>预约时长</label><div className="mt-2 flex flex-wrap gap-2">{[1,2,3,4,5].map(h=><button className={`choice !px-4 !py-2 ${duration===h?"active":""}`} key={h} onClick={()=>setDuration(h)}>{h} 小时</button>)}</div><button className="btn btn-primary mt-7 w-full" onClick={()=>setStep(2)}>查看可预约时间 <ChevronRight className="inline h-4 w-4"/></button></>}
{step===2&&<><button className="mb-4 text-sm font-bold muted" onClick={()=>setStep(1)}><ChevronLeft className="inline h-4 w-4"/> 返回</button><h2 className="text-2xl font-black">选择开始时间</h2><p className="mt-1 text-sm muted">{date} · {typeLabels[type]} · {duration} 小时</p><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-4">{shown.map(s=>{const tm=s.start_time.slice(0,5),full=s.availability==="FULL";return <button disabled={full} onClick={()=>setStart(tm)} className={`choice !p-3 text-center ${start===tm?"active":""}`} key={tm}><span className="block font-black">{tm}</span><span className={`mt-1 block text-[11px] ${full?"text-red-500":s.availability==="ONE_LEFT"?"text-amber-600":"text-emerald-700"}`}>{full?"已满":s.availability==="ONE_LEFT"?"仅剩1组":"可预约"}</span></button>})}</div><button disabled={!start} className="btn btn-primary mt-7 w-full" onClick={()=>setStep(3)}>继续填写信息 <ChevronRight className="inline h-4 w-4"/></button></>}
{step===3&&<><button className="mb-4 text-sm font-bold muted" onClick={()=>setStep(2)}><ChevronLeft className="inline h-4 w-4"/> 返回</button><h2 className="text-2xl font-black">确认预约</h2>{type!=="PRIVATE"&&<div className="mt-5"><label className="text-sm font-bold"><Users className="mr-2 inline h-4 w-4"/>陪同人数</label><select className="field mt-2" value={companions} onChange={e=>setCompanions(+e.target.value)}>{[0,1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} 人</option>)}</select></div>}<div className="mt-4"><label className="text-sm font-bold"><Camera className="mr-2 inline h-4 w-4"/>是否需要租相机</label><select className="field mt-2" value={camera} onChange={e=>setCamera(e.target.value)}>{["不需要","DJI Pocket 3","Canon M50 Mark II","不确定，到店再选"].map(x=><option key={x}>{x}</option>)}</select><p className="mt-1 text-xs muted">相机租金到店另付，不计入预约价格。</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className="field" placeholder="姓名 / 昵称" value={name} onChange={e=>setName(e.target.value)}/><input className="field" placeholder="手机号 / 微信号" value={contact} onChange={e=>setContact(e.target.value)}/></div><label className="mt-4 block text-sm font-bold">预约备注（选填）<textarea className="field mt-2" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="可填写到店准备、拍摄需求等信息"/></label><div className="mt-5 rounded-2xl bg-[#fff1f6] p-4"><div className="flex justify-between text-sm"><span>{typeLabels[type]} · {duration}小时</span><b>{price?money(price.base_price):"—"}</b></div>{companions>0&&<div className="mt-2 flex justify-between text-sm"><span>陪同 {companions} 人</span><b>{price?money(price.companion_total):"—"}</b></div>}<div className="my-3 border-t border-[var(--line)]"/><div className="flex justify-between"><b>预约总价</b><b className="text-xl">{price?money(price.standard_price):"—"}</b></div><div className="mt-2 flex justify-between text-sm muted"><span>需付定金</span><span>{price?money(price.deposit_due):"—"}</span></div><div className="mt-1 flex justify-between text-sm muted"><span>到店待付</span><span>{price?money(+price.standard_price-+price.deposit_due):"—"}</span></div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={!name.trim()||!contact.trim()||loading} className="btn btn-primary mt-5 w-full" onClick={submit}>{loading?"正在锁定…":<><Check className="mr-1 inline h-4 w-4"/>确认预约并锁定15分钟</>}</button></>}
</div></div>}
